name: Check for Updates

on:
  schedule:
    - cron: "58 5 * * *"
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  TARGET_TAG: latest

jobs:
  version-check:
    name: Compare Local and Upstream Versions
    runs-on: ubuntu-24.04
    permissions: write-all
    outputs:
      update_required: ${{ steps.compare_versions.outputs.update_required }}
      current_version: ${{ steps.get_release_version.outputs.current_version }}
      upstream_version: ${{ steps.get_upstream_version.outputs.upstream_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Load current version
        uses: actions/cache/restore@v4
        with:
          key: current_version
          path: current_version_file
          fail-on-cache-miss: false

      - name: Get current version
        id: get_current_version
        run: |
          set -e
          echo "Getting current version"
          if [ -f current_version_file ]; then
            CURRENT_VERSION=$(cat current_version_file)
          else
            CURRENT_VERSION="no-version"
          fi
          echo "Current version: $CURRENT_VERSION" >> $GITHUB_STEP_SUMMARY
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Get upstream version
        id: get_upstream_version
        run: |
          set -e
          echo "Getting upstream version"
          UPSTREAM_VERSION=$(wget -q "https://hub.docker.com/v2/repositories/library/mediawiki/tags/${{ env.TARGET_TAG }}" -O - | jq '.digest' )
          TAGS_JSON="$(wget -q "https://hub.docker.com/v2/repositories/library/mediawiki/tags" -O -)"
          LATEST_TAGS_JSON="$(echo $TAGS_JSON | jq '.results | map(select(.digest == '$UPSTREAM_VERSION')) | map("type=raw,enable=true,value="+.name)' | tr '\n' ' ')"
          echo "latest_tags_json=$LATEST_TAGS_JSON" >> $GITHUB_OUTPUT
          LATEST_TAGS="$(echo $TAGS_JSON | jq '.results | map(select(.digest == '$UPSTREAM_VERSION')) | map(.name)| join("\n")' | sed 's/"//g')"
          FULL_VERSION=$(echo -e $LATEST_TAGS | grep '^[0-9]\+\.[0-9]\+\.[0-9]\+$')
          EXTENSION_VERSION=$(echo $FULL_VERSION | sed 's/^\([0-9]\+\.[0-9]\+\).*/\1/' | sed 's/\./_/g')
          echo -n $UPSTREAM_VERSION > current_version_file
          echo "Upstream hash: $UPSTREAM_VERSION" >> $GITHUB_STEP_SUMMARY
          echo "Upstream version: $FULL_VERSION" >> $GITHUB_STEP_SUMMARY
          echo "upstream_version=$UPSTREAM_VERSION" >> $GITHUB_OUTPUT
          echo "extension_version=REL$EXTENSION_VERSION" >> $GITHUB_OUTPUT
          echo "Extension version: REL$EXTENSION_VERSION" >> $GITHUB_STEP_SUMMARY
          echo "full_version=$FULL_VERSION" >> $GITHUB_OUTPUT

      - name: Cache current version
        uses: actions/cache/save@v4
        with:
          key: current_version
          path: current_version_file

      - name: Compare versions
        id: compare_versions
        env:
          CURRENT_VERSION: ${{ steps.get_current_version.outputs.current_version }}
          UPSTREAM_VERSION: ${{ steps.get_upstream_version.outputs.upstream_version }}
        run: |
          set -e
          echo "update_required=true" >> $GITHUB_OUTPUT
          exit
          if [ "$UPSTREAM_VERSION" == "$CURRENT_VERSION" ]; then
              echo "Current version $CURRENT_VERSION is equal to Upstream version $UPSTREAM_VERSION."
              echo "No update required." >> $GITHUB_STEP_SUMMARY
              echo "update_required=false" >> $GITHUB_OUTPUT
          else
              echo "Upstream version $UPSTREAM_VERSION is newer than Current version $CURRENT_VERSION."
              echo "Creating release... :rocket:" >> $GITHUB_STEP_SUMMARY
              echo "update_required=true" >> $GITHUB_OUTPUT
          fi

      # Set up QEMU for cross-platform builds
      - name: Set up QEMU
        if: ${{ steps.compare_versions.outputs.update_required == 'true' }}
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        if: ${{ steps.compare_versions.outputs.update_required == 'true' }}
        uses: docker/setup-buildx-action@v3.11.1

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: ${{ steps.compare_versions.outputs.update_required == 'true' }}
        uses: docker/login-action@v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        if: ${{ steps.compare_versions.outputs.update_required == 'true' }}
        id: meta
        uses: docker/metadata-action@v5.10.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto
          tags: |-
            ${{ join(fromJSON(steps.get_upstream_version.outputs.latest_tags_json), '
            ') }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        if: ${{ steps.compare_versions.outputs.update_required == 'true' }}
        id: build-and-push
        uses: docker/build-push-action@v6
        env:
          VERSION: ${{ steps.get_upstream_version.outputs.full_version }}
          EXTENSION_BRANCH: ${{ steps.get_upstream_version.outputs.extension_version }}
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ steps.get_upstream_version.outputs.full_version }}
            EXTENSION_BRANCH=${{ steps.get_upstream_version.outputs.extension_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
