name: Check for Updates

on:
  schedule:
    - cron: "58 5 * * *"
  workflow_dispatch:

jobs:
  version-check:
    name: Compare Local and Upstream Versions
    runs-on: ubuntu-24.04
    permissions: write-all
    outputs:
      update_required: ${{ steps.compare_versions.outputs.update_required }}
      current_version: ${{ steps.get_release_version.outputs.current_version }}
      upstream_version: ${{ steps.get_upstream_version.outputs.upstream_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Load current version
        uses: actions/cache/restore@v4
        with:
          key: current_version
          path: current_version_file
          fail-on-cache-miss: false

      - name: Get current version
        id: get_current_version
        run: |
          set -e
          echo "Getting current version"
          if [ -f current_version_file ]; then
            CURRENT_VERSION=$(cat current_version_file)
          else
            CURRENT_VERSION="no-version"
          fi
          echo "Current version: $CURRENT_VERSION" >> $GITHUB_STEP_SUMMARY
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Get upstream version
        id: get_upstream_version
        run: |
          set -e
          echo "Getting upstream version"
          UPSTREAM_VERSION=$(wget -q "https://hub.docker.com/v2/repositories/library/mediawiki/tags/latest" -O - | jq '.digest' )
          echo -n $UPSTREAM_VERSION > current_version_file
          echo "Upstream version: $UPSTREAM_VERSION" >> $GITHUB_STEP_SUMMARY
          echo "upstream_version=$UPSTREAM_VERSION" >> $GITHUB_OUTPUT

      - name: Cache current version
        uses: actions/cache/save@v4
        with:
          key: current_version
          path: current_version_file

      - name: Compare versions
        id: compare_versions
        env:
          CURRENT_VERSION: ${{ steps.get_current_version.outputs.current_version }}
          UPSTREAM_VERSION: ${{ steps.get_upstream_version.outputs.upstream_version }}
        run: |
          set -e
          if [ "$UPSTREAM_VERSION" == "$CURRENT_VERSION" ]; then
              echo "Current version $CURRENT_VERSION is equal to Upstream version $UPSTREAM_VERSION."
              echo "No update required." >> $GITHUB_STEP_SUMMARY
              echo "update_required=false" >> $GITHUB_OUTPUT
          else
              echo "Upstream version $UPSTREAM_VERSION is newer than Current version $CURRENT_VERSION."
              echo "Creating release... :rocket:" >> $GITHUB_STEP_SUMMARY
              echo "update_required=true" >> $GITHUB_OUTPUT
          fi

      - name: Create release
        if: ${{ steps.compare_versions.outputs.update_required == true }}
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
          NEW_VERSION: ${{ steps.get_upstream_version.outputs.upstream_version }}
        with:
          tag_name: ${{ steps.get_upstream_version.outputs.upstream_version }}
          body: MediaWiki version bump
          generate_release_notes: true
          append_body: true
          make_latest: true
